### ISSUE TITLE
R installation failed

### ISSUE THREAD

**Issue by sohinir** [gbradburd/conStruct#1]
When following your readme instructions to install conStruct using install_github() [on R 3.2.4], I got the following error: Error: Does not appear to be an R package (no DESCRIPTION).

**Comment by petrelharp** [comment]
That's odd - it works for me.  Are you sure you did:
```
install_github("gbradburd/conStruct/code/conStruct",build_vignettes=TRUE)
```
... you'd get that error if you missed out the final `code/conStruct` in the path.

**Comment by sohinir** [comment]
I did do that command (although with build_vignettes=T, not TRUE); when I
reran with the command you suggested I still had trouble installing but
with different errors. I'll report back after upgrading my R version. For
now you might want alarms to sound if a particular R version is needed.

**Comment by gbradburd** [comment]
Hmm that's interesting - in the DESCRIPTION file the dependency is listed as R (>= 3.3.2), so I'm surprised it didn't give you an informative error about why the install failed.  My guess is that it had something to do with the version of devtools, but I don't know for sure.  I'm going to list this issue as closed for now, but please open a new issue if you continue to have problems after you update R.
