### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by zfuller5280** [gbradburd/conStruct#13]
Hi,
I am trying to install conStruct using the instructions provided. I am using the following command:
```
library(devtools)
install_github("gbradburd/conStruct",build_vignettes=TRUE)
```
However, after it looks like it finished compiling, I get the following error:
```
** testing if installed package can be loaded
Error: package or namespace load failed for ‘conStruct’ in .doLoadActions(where, attach):
 error in load action .__A__.1 for package conStruct: is(module, "character"): object 'm' not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/conStruct’
Installation failed: Command failed (1)
```
I am using R version 3.5.1

Do you have any idea of what could be causing this issue, and how to go about correctly installing conStruct.
Thanks!

**Comment by gbradburd** [comment]
Hi Zach,

I haven't seen this error before (congrats!), so I have a bunch of questions:

1. Do you get any warnings before that error?
2. What OS are you using?
3. Are you running Rstudio or R, and, if the latter, are you running through shell?
4. Do you also get this error when you try to install the dev branch?

`devtools::install_github("gbradburd/conStruct", ref="dev", build_vignettes=TRUE)`

5. Does the error go away if you install using the command:

`devtools::install_github("gbradburd/conStruct",build_vignettes=TRUE,args = "--preclean")`

Thanks, and let me know what you find.

**Comment by zfuller5280** [comment]
Thanks for the response and glad to be the first with this error!
1. Yes, it does appear that there a number of warnings before the error. They all take the form as follows:
```
/var/folders/vr/m5tjw4pn7jdfycsp55cjgdfw0000gn/T//ccuCsiza.s:542552:11: warning: section "__datacoal_nt" is deprecated
        .section __DATA,__datacoal_nt,coalesced
                 ^      ~~~~~~~~~~~~~
/var/folders/vr/m5tjw4pn7jdfycsp55cjgdfw0000gn/T//ccuCsiza.s:542552:11: note: change section name to "__data"
        .section __DATA,__datacoal_nt,coalesced
                 ^      ~~~~~~~~~~~~~
```
The only thing that changes between error messages are the numbers that come after `ccuCsiza.s:`.
2. My OS is Mac OS X Sierra 10.12.6
3. I'm using R Studio Version 1.1.456
4 & 5. I tired both of the installation commands suggested, and unfortunately the same error is generated from each.

**Comment by zfuller5280** [comment]
Thanks for pointing me in the direction of looking at my g++ version. I had updated the compiler, but it turns out that R was using a different version defined in `~/.R/makevars`. Changing this to the most recent version of g++ solved the issue. Appreciate the help!
