### ISSUE TITLE
structure2conStruct

### ISSUE THREAD

**Issue by taniachavarria79** [gbradburd/conStruct#15]
Hello,

I'm trying to use conStruct to re-analyze my data as the reviewers in the Molecular ecology suggested for my paper.
I used spider to convert my vcf file to structure and in addition Stacks give a structure data format.
The problem is that the arrangement is two rows for each individual and one column for loci. As you said in the manual there has to be two columns for each loci and one for an individual and I do not know who to do this? How you got your structure data to be arrange like that? 
There is another way to convert data to use your program per example convert vcf data?
I will appreciate a lot if you can help me with this issue
Thanks

**Comment by petrelharp** [comment]
Thanks for the example data. Please write out exactly what the rows and columns in that sheet are.

**Comment by taniachavarria79** [comment]
Hi,
The first column is the individuals as they are biallelic data there is two rows per individual. The second column is the population number, and the loci information start in the column three. 

Thanks so much for your help!

**Comment by petrelharp** [comment]
I don't understand yet: to be concrete, in the row labeled `tarcoles_2_paired_YWAR` and the column labeled `53923_95` there is the number `3`. What does that mean? Is this microsat data?

**Comment by taniachavarria79** [comment]
Hello,


this are SNPs but is Raq-seq data. So there is small sequence cuts, 3 means that the individual has 3 of the 4 possibles nucleotides changes in that particular loci for that allele.


Thanks

________________________________

**Comment by taniachavarria79** [comment]
Hello,

Did you see my past message? I did explain to you that the data are SNPs. Can you still help me to get the data arrange correctly to use your program?


Thanks again for your help!

________________________________

**Comment by gbradburd** [comment]
Hi and sorry for the delay in getting back to you.  I think I'm now more confused about what the values in your data represent.  You say above 

> 3 means that the individual has 3 of the 4 possibles nucleotides changes in that particular loci for that allele.

Do you mean that the individual is tri-allelic?  Or does the "3" value represent a particular nucleotide identity (e.g., 1="A", 2="C", 3="G", 4="T")?

**Comment by taniachavarria79** [comment]
Sorry I can not send my vcf data github does not allow this!

But is the second one: does the "3" value represent a particular nucleotide identity (e.g., 1="A", 2="C", 3="G", 4="T")


Thanks so much for your help!

________________________________

**Comment by gbradburd** [comment]
Ok and "0" is missing data?

**Comment by taniachavarria79** [comment]
Yes!


Thanks

________________________________

**Comment by gbradburd** [comment]
Ok I've updated the `structure2conStruct` function so that it should allow you to convert a STRUCTURE data file that is either has one row or two rows per sample.  You'll have to reinstall conStruct from the github repo

`library(devtools)`
`install_github("gbradburd/conStruct",build_vignettes=TRUE)`

A few things to note:

1. Your dataset can only consist of bi-allelic loci, so if you have any loci with more than 2 alleles, you should drop them before running `structure2conStruct`.
2. The STRUCTURE data file must be a text file (rather than a spreadsheet), and there can be no lines of text in the file before your dataset begins.  There are instructions in the `format-data` vignette on how to convert a spreadsheet to an appropriate text format.
3. There's now an argument in `structure2conStruct` called `onerowperind`, so you'll want to set that to `FALSE` for your data file.

If that works for you, great!  If not, please let me know how it fails and what error messages you get.

**Comment by taniachavarria79** [comment]
Thanks so much!  I will try it and let you know! Thanks again for all your help ! I really appreciate!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gbradburd** [comment]
Can you send me what's printed to the screen when you type

`library(conStruct)`
`structure2conStruct`

into the R console?  And, can you also send me the full command you're entering into R that's resulting in that error message?

**Comment by taniachavarria79** [comment]
This is what R put in the console:

> library(devtools)
> install_github("gbradburd/conStruct",build_vignettes=TRUE)
Downloading GitHub repo gbradburd/conStruct@master
from URL https://api.github.com/repos/gbradburd/conStruct/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.5.1 was found. (Only the following incompatible version(s) of Rtools were found:3.5)

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/.
Installing conStruct
"C:/PROGRA~1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/fortu/AppData/Local/Temp/Rtmpu42uxJ/devtools3d2c16053e31/gbradburd-conStruct-c3eb806"  \
  --library="C:/Users/fortu/Documents/R/win-library/3.5" --install-tests

* installing *source* package 'conStruct' ...
** libs

*** arch - i386
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'conStruct'
* removing 'C:/Users/fortu/Documents/R/win-library/3.5/conStruct'
* restoring previous 'C:/Users/fortu/Documents/R/win-library/3.5/conStruct'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\fortu\Documents\R\win-library\3.5\00LOCK-gbradburd-conStruct-c3eb806\conStruct\libs\x64\conStruct.dll to C:\Users\fortu\Documents\R\win-library\3.5\conStruct\libs\x64\conStruct.dll: Permission denied
In R CMD INSTALL
Installation failed: Command failed (1)


This is the command I'm using:


conStruct.data <- structure2conStruct(infile = "C:/Users/fortu/Desktop/batch_1newdata.str",
                                      start.loci = 3,
                                      missing.datum = 0,
                                      ONEROWPERIND = FALSE,
                                      outfile = "C:/Users/fortu/Desktop/myConStructData")



Thanks for your help!

________________________________

**Comment by gbradburd** [comment]
A few things:

1) It looks like you need to install the new version of Rtools in order to install the conStruct R package.  So that should be your first step, because you won't be able to access the updated function unless you can install the updated package.

2) Function arguments in R are generally case-sensitive, so once you've downloaded the updated package, you should specify `onerowperind = FALSE` and not `ONEROWPERIND = FALSE`.  If in doubt, you can check the documentation for the function using the command `help(structure2conStruct)`.

3) Above, I had asked to see R console's output when you enter the command `structure2conStruct`.  If, after successfully installing the new version of conStruct from github, you are still getting errors, please also copy and paste the output of that command into your post.

**Comment by taniachavarria79** [comment]
Okay thanks! I will try that!

________________________________

**Comment by taniachavarria79** [comment]
Sorry to bug you again. Now that I have everything install I got this message 
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 15309 elements

when i run this command:
conStruct.data <- structure2conStruct(infile = "C:/Users/fortu/Desktop/batch_1newdata.str",
                                      start.loci = 3,
                                      missing.datum = 0,
                                      onerowperind = FALSE,
                                      outfile = "C:/Users/fortu/Desktop/myConStructData")

Usually this error get fix with read delimited but as in the code to convert the data said that input file should be a link.

What i can do?

Thanks again for your help!

**Comment by gbradburd** [comment]
My guess is that you have extraneous lines at the top of your data file. Please read the documentation carefully (you can also refer to the "format-data" vignette) to make sure your data fit the required format.

**Comment by taniachavarria79** [comment]
[test.txt](https://github.com/gbradburd/conStruct/files/2448417/test.txt)
Sorry is not working I even make a test tabdelimited file just with few loci. I check them in windows note pad and in textwrangler in Mac, I change individuals names and loci names, and nothing! Here is my test.text. Can you look it to see if you can run it? 

thanks again for your help!

**Comment by gbradburd** [comment]
Yup, you just have to delete the first line of the file, as mentioned above.  Since this doesn't seem to be an issue with conStruct any more, I'm going to close this issue. Please re-open it if you find an error with the method I provided.  Good luck!

**Comment by quinn-ca** [comment]
[n10_autosomal_genstr_iterativefiltered_populations_rmRelated_numericpop_str.txt](https://github.com/gbradburd/conStruct/files/11042508/n10_autosomal_genstr_iterativefiltered_populations_rmRelated_numericpop_str.txt)

Hello, I'm getting the same error about an incorrect number of elements when using structure2conStruct.

`Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 29556 elements`

The code I ran is:
```
conStruct.data <- structure2conStruct(infile = "/inpath/n10_autosomal_genstr_iterativefiltered_populations_rmRelated_numericpop_str.txt",
                                        onerowperind = FALSE,
                                        start.loci = 3,
                                        start.samples = 1,
                                        missing.datum = 0,
                                        outfile = "/outpath/construct")
  
```


I tried using a `.structure` file extension (directly from Stacks), which my mac doesn't recognize as a .txt file, and also converted it to a `.txt` file extension, as in the example here. I got the error with both file types. 

I've attached the first 10 lines of my structure dataset. From the vignette, it looks like my infile should have a row (ie., column header) for the loci, is that correct? Or should I delete the first line with the loci names?

I appreciate your help,
Quinn

**Comment by quinn-ca** [comment]
I may have answered my own question by changing `start.samples` to `2`. I thought that the locus names would be considered the header row and so not included in the start.samples count, but the matrix successfully loaded when I changed it to 2.
