### ISSUE TITLE
Error in validate.n.samples(data.block)

### ISSUE THREAD

**Issue by rpercino** [gbradburd/conStruct#22]
Hi, 
When I try to run conStruct, after I built myConStructData, it pop up an error: checking data.block
Error in validate.n.samples(data.block): the number of samples is not consistent across entries in the data.block.
Here is my file 
[denovo30.txt](https://github.com/gbradburd/conStruct/files/3450060/denovo30.txt)
[coords.txt](https://github.com/gbradburd/conStruct/files/3450064/coords.txt)
I do not the where is it wrong with the file. 
Thank you in advance, 
r

**Comment by petrelharp** [comment]
It looks like you have 64 samples in "denovo30.txt" and only 10 coordinates; you should have coordinates for every sample. Maybe you're trying to specify which sample is at which coordinate using the labels in the first column? If this isn't the problem, please post the code that gave you the error.

**Comment by rpercino** [comment]
Thank you! I going to fixed the coordinates file

**Comment by petrelharp** [comment]
Great! I will close this issue; please re-open if you still have a problem.
