### ISSUE TITLE
r-hat and Tail and Bulk Effective Sample Size Warnings

### ISSUE THREAD

**Issue by thomlmarshall** [gbradburd/conStruct#25]
Hi,
I'm able to run my conStruct analysis, but I'm struggling to eliminate the following warnings:

3: The largest R-hat is 1.08, indicating chains have not mixed.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#r-hat 
4: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#bulk-ess 
5: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.
Running the chains for more iterations may help. See
http://mc-stan.org/misc/warnings.html#tail-ess 

The solution would seem to be increasing the number of iterations, but I've found that these warnings do not change linearly as I increase the iterations. Some drop out as I try more iterations, but then come back when I try an even larger number of iterations. I've gone as high as 20,000 iterations and still got the r-hat and tail ESS warning. So far, I haven't been able to run an analysis without some of these issues. Any suggestions on how to address this? Is this even something to be especially concerned with?
Thanks for the help!

**Comment by petrelharp** [comment]
Well, as perhaps you know, those things indicate that the Markov chain may not be properly exploring parameter space, which is always a worry with Monte Carlo-based methods. Have you looked at the trace plots and autocovariances? How many chains are you running? The stochasticity you are observing in r-hat and ESS might be a result of running only a few (2?) chains, and depending on where they start out?

In general, though, this is tricky.

**Comment by gbradburd** [comment]
Hi Thom - just following up to say "ditto" what Peter said: I'd visually examine the trace plots and assess convergence both within and between runs.  And, it may be that you'll get more bang for your buck running multiple, independent runs rather than 1 long run.  Do your runs look pretty wonky?

**Comment by gbradburd** [comment]
Hi Thom - is this issue still unresolved for you?  If not, I'll go ahead and close it out.
