### ISSUE TITLE
High Rhat across replicate runs

### ISSUE THREAD

**Issue by gbradburd** [gbradburd/conStruct#26]
Hi @oscaredd - I think this is an important point so I'm splitting it out into its own issue so other users can find it more easily. I'm quoting your original post below, and then I'll respond to it in it's own thread.

> Hi there!
>
> I would like to get your advice for a problem I have with the mixing of chains in my analysis. My dataset contains ~600 SNPs (those have shown nice results with traditional clustering methods) with 64 "samples", with allele frequencies calculated from one or several individuals.
For both discrete and spatial methods in conStruct, I keep getting both R-hat (it has reached ~4.5 in some cases) and the "divergent transitions after warmup" warnings. So far I've tried increasing iterations from 10K to 100K, increasing `adapt _delta` up to 0.99, run 2 or 4 chains. In all cases I've ran 2 independent analyses for each K (1-8). To this moment, I can only think of these possibilities: 1) need more SNPs (I could go up to ~43K SNPs, but then some of those will probably by linked), and 2) need to reduce complexity by reducing the number of samples.
>
> Thanks in advance for your help!

_Originally posted by @oscaredd in https://github.com/gbradburd/conStruct/issues/17#issuecomment-545926895_

**Comment by gbradburd** [comment]
My first guess is that the ordering of the “layers” in conStruct isn’t consistent across independent chains, which is resulting in inflated an Rhat.  E.g., if Layer 1 in chain 1 corresponds to Layer 3 in chain 2, both chains might be converging on basically the same stationary distribution, but you’ll see really high variance across chains relative to that within each of your chains.  Do you see Rhat > 1 between chains when K=1?  If not, the “label switching” between chains may be the issue.

More generally, if you have more SNPs, I’d recommend using them unless they're low quality (lots of missing data, or high uncertainty in genotype calls).  After the initial calculation of the sample covariance, conStruct should run as quickly with 600 SNPs as 40K SNPs, or however many you get after you thin for LD.

Hope that's helpful!

**Comment by oscaredd** [comment]
Thank you for the reply! For K=1 I didn't see the R-hat warning, hence I imagine R-hat < 1.
Then, what if chains are actually not converging? I checked the trace plots and they do not seem to wander around the same value from K=2 and on.

Thank you.

**Comment by gbradburd** [comment]
When you say the different chains don't seem to be converging on the same stationary distribution, what parameters/quantities do you see that for?  Posterior probability?  Or admixture proportions?  And if the latter, is that before or after you try to deal with the label-switching? (If you haven't already seen it, note that you can use the `match.layers.x.runs()` function to deal with label switching across different runs (or different values of _K_).)

**Comment by oscaredd** [comment]
I thank you for the advice on the layer matching, which seems to be almost and imperative to get congruent pie plots.
The problem of convergence I am referring to, is the one I see in the trace plots that conStruct generates (attached). As I interpret those plots (please, correct me if I'm wrong), it looks like the chains are not finding the same solution. The situation seems even worse for chains 1 and 2. Can you please suggest a way to improve them. As I mentioned, I already tried increasing `adapt_delta` up to 0.99, and ran from 10,000 to 100,000 iterations.

[spK3_trace.plots.chain_1.pdf](https://github.com/gbradburd/conStruct/files/3772779/spK3_trace.plots.chain_1.pdf)
[spK3_trace.plots.chain_2.pdf](https://github.com/gbradburd/conStruct/files/3772780/spK3_trace.plots.chain_2.pdf)
[spK3_trace.plots.chain_3.pdf](https://github.com/gbradburd/conStruct/files/3772781/spK3_trace.plots.chain_3.pdf)
[spK3_trace.plots.chain_4.pdf](https://github.com/gbradburd/conStruct/files/3772782/spK3_trace.plots.chain_4.pdf)

**Comment by gbradburd** [comment]
Hmm none of these chains seems to be mixing especially well.  Are these results from a run with `n.iter=1e4` or `1e5`?  If so, I can think of two possible sources of difficulty:

1) there may be insufficient signal in your 600 SNPs to parameterize the model.  I don't _think_ that's what's going on, because then I'd expect to see posterior parameter distributions that mix well but largely recover their priors.  However, it may be worth exploring how the analyses look when you include a larger proportion of your 43K snps (as mentioned above, no real reason not to, unless data quality goes way down).

2) One interesting thing is that your `alphaD` parameter estimates are uniformly tiny.  Is the range of pairwise geographic distances between your samples really large (like, a few regions that are heavily sampled locally, but that are really far away from each other)?  `conStruct` attempts to standardize geographic distance under the hood by dividing it by its standard deviation, but in cases when the range of geographic separation is huge, it may not be able to do enough.  One option in that case is to divide `geoDist` by its maximum when you feed it to `conStruct`, so it only ranges between 0 and 1.

If neither of those fixes the issue, please send me the data object you're analyzing and the script you're using to run the analysis and I'll take a look.

**Comment by oscaredd** [comment]
Thanks for the advice. These plots resulted from `n.iter=1e4`. 
I just started the new runs with standardized pairwise distances as suggested. One thing though, is that I have the same convergence problems in the non-spatial runs, hence it look like the standardized geoDists may help, but not solve it.
Oscar.

**Comment by gbradburd** [comment]
Hi Oscar,

Yeah if you're seeing this issue with the non-spatial run, standardizing the distances may not help.  I'd try to add in more of your data and see if you still get the same issues, but other than that, I don't know if I have any good advice, as I haven't seen this issue before.

**Comment by gbradburd** [comment]
Hi Oscar - is this issue still unresolved for you?  If not, I'll go ahead and close it out.

**Comment by oscaredd** [comment]
Hello Dr. Bradburd – Thank you for following up on this. I decided to continue with the results of the non-spatial analysis. 
You can close it now. Thank you!
