### ISSUE TITLE
Error Running ConStruct

### ISSUE THREAD

**Issue by DawnRobin** [gbradburd/conStruct#4]
Hi, I'm getting the following error as I work through the vignette for how to run conStruct.  It is the same when I copy and past the code for the spatial and nonspatial model.  I am running R Studio 1.1.423 and R 3.4.3.  

Thanks for your help. I appreciate what you have done.
Dawn

Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! Warning message:
running command 'make -f "C:/PROGRA~1/R/R-34~1.3/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="file2bc05c09657a.dll" WIN=64 TCLBIN=64 OBJECTS="file2bc05c09657a.o"' had status 127 
In addition: Warning messages:
1: running command '"C:/PROGRA~1/R/R-34~1.3/bin//R" CMD config CXX' had status 1 
2: running command 'C:/PROGRA~1/R/R-34~1.3/bin/x64/R CMD SHLIB file2bc05c09657a.cpp 2> file2bc05c09657a.cpp.err.txt' had status 1 

![image](https://user-images.githubusercontent.com/37131495/37073053-f81f7524-2170-11e8-9c4e-7d356ed83ee5.png)

**Comment by petrelharp** [comment]
According to [this thread](https://groups.google.com/forum/#!topic/stan-users/tbhjcjF-Egs) the code `127` means "can't find some program", probably the compiler - see the notes in that thread.  Either way, this is some problem with the rstan installation.

**Comment by gbradburd** [comment]
Agree with @petrelharp that this seems to be an issue with the installation of rstan, rather than conStruct specifically.  Have you checked whether you can run any of the example models in the rstan vignette?

**Comment by petrelharp** [comment]
I am closing this; @DawnRobin please re-open if this is actually a conStruct bug.
