### ISSUE TITLE
number of samples is not consistent across entries

### ISSUE THREAD

**Issue by SheaML** [gbradburd/conStruct#5]
Hi,

I'm getting the following error when trying to execute conStruct:

##
\>conStruct(spatial=TRUE,K=2,freqs=taftmat,geoDist=pop_dists,coords=pop_coords,prefix="spK2")
checking data.block

Error in validate.n.samples(data.block) : 
the number of samples is not consistent 
				across entries in the data.block
##

I'm attaching my distance matrix, coordinates, and allele frequency matrix:
[geoDist.txt](https://github.com/gbradburd/conStruct/files/1814710/geoDist.txt)
[pop_coords.txt](https://github.com/gbradburd/conStruct/files/1814711/pop_coords.txt)
[taftmat.txt](https://github.com/gbradburd/conStruct/files/1814712/taftmat.txt)

Thanks for any advice!

**Comment by petrelharp** [comment]
Looks to me like you need to transpose your matrix of frequencies (`taftmat`) before you pass it in:
```
conStruct(spatial=TRUE,K=2,freqs=t(taftmat),geoDist=pop_dists,coords=pop_coords,prefix="spK2")
```

If not, please post code for how you get those files into the variables.

**Comment by SheaML** [comment]
The matrix is formatted following the vignette on data structure (populations/samples as rows, loci as columns). I've tried transposing it but the same error is produced. The files can be read into the variables like so:

as.matrix(read.table("./geoDist.txt")) -> pop_dists
as.matrix(read.table("./pop_coords.txt")) -> pop_coords
as.matrix(read.table("./taftmat.txt")) -> taftmat

**Comment by petrelharp** [comment]
I do not get this error:
```
R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"

> library(conStruct)
Loading required package: rstan
Loading required package: ggplot2
Loading required package: StanHeaders
rstan (Version 2.17.3, GitRev: 2e1f913d3ca3)
For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores()).
To avoid recompilation of unchanged Stan programs, we recommend calling
rstan_options(auto_write = TRUE)
> as.matrix(read.table("./geoDist.txt")) -> pop_dists
> as.matrix(read.table("./pop_coords.txt")) -> pop_coords
> as.matrix(read.table("./taftmat.txt")) -> taftmat
> conStruct(spatial=TRUE,K=2,freqs=taftmat,geoDist=pop_dists,coords=pop_coords,prefix="spK2")

checking data.block

	reading 16 samples
	reading 847 loci

checking specified model


user has specified a spatial model with 2 layer(s)
```

Please try re-installing conStruct; if that doesn't work then please post the output of `sessionInfo()`; the code you ran; and the output.  Good luck!

**Comment by SheaML** [comment]
An update to R 3.4.3 and re-installation of conStruct fixed the issue. Thanks.
