### ISSUE TITLE
AF sometimes 1

### ISSUE THREAD

**Issue by laurenhamm** [gbradburd/conStruct#55]
To run construct with alt allele frequency at the population level while being consistent across populations, sometimes the frequency is 1. 
This throws an error. Is there any way to get around that?

**Comment by gbradburd** [comment]
Hm I'm not sure I follow the situation.  Is the frequency of the counted allele 1 across _all_ your samples?  If so, that shouldn't throw an error but it will get dropped when the frequency data are being processed (inside `conStruct:::process.freq.data`).  What error are you getting?

**Comment by laurenhamm** [comment]
You can close it for now! We are working on realigning our data to a new
reference so it’ll be a while before I get around to rerunning everything
through the ConStruct pipeline.
Thanks,
Ren
