### ISSUE TITLE
Is parallelization possible?

### ISSUE THREAD

**Issue by sbreitbart** [gbradburd/conStruct#57]
Is it possible to parallelize the models? I'm very new to parallelization and am trying to get my bearings.

For example, I'd like to parallelize this to run on multiple cores:

```
conStruct(spatial = FALSE, 
                    K = 2, 
                    freqs = allele_frqs, 
                    geoDist = NULL, 
                    coords = coords,
                    prefix = "nsp_K2_iter5000_chains5",
                    n.chains = 5,
                    n.iter = 5000)
```

Thanks so much,
Sophie

**Comment by sbreitbart** [comment]
Solved: https://stackoverflow.com/questions/76591840/can-i-parallelize-a-bayesian-hierarchical-model-using-mcmc-simulation-specifica

**Comment by gbradburd** [comment]
Sorry for the slow reply (traveling w/ fam), but glad you got this sorted!
