### ISSUE TITLE
In cross-validation, two best-performing replicates of the same model show very different ancestry

### ISSUE THREAD

**Issue by Dahn-YoungDong** [gbradburd/conStruct#59]
<img width="1781" alt="Screenshot 2023-08-03 at 2 43 17 PM" src="https://github.com/gbradburd/conStruct/assets/57223771/ccc01517-c095-4e8b-930d-4375ab57ff16">

Dear Prof. Bradburd,
Left column are two best performing replicates from the K=2 in non-spatial model, and right column in spatial model K=6, MCMC is 1e5, replicates are 10 for each model (19 populations, and 20K SNPS).

![00001b](https://github.com/gbradburd/conStruct/assets/57223771/d8422e28-f1e5-4692-b437-386f3521906d)

After population orders are kept the same, the two replicates don't show similar ancestry assignment. So in data interpretation, which one should I use?

Best,
Dahn-young

**Comment by gbradburd** [comment]
Hi Dahn-young,

Huh that's interesting!  I've never seen a cross-validation analysis with results that look like that and I'm not quite sure what to make of them.  Can you share the code you're using to run `x.validation`?

W/r/t which replicate you should use, my answer would be neither.  Each cross-validation replicate is using only a subset of the data (the training set).  So, if you want to give final results for a single model that you've selected, you should run that model using all the data (with the `conStruct` function, rather than with `x.validation`).

**Comment by Dahn-YoungDong** [comment]
Thanks I will get back to you once I include more sampling locations.

**Comment by Dahn-YoungDong** [comment]
> > Hi Dahn-young,
> > Huh that's interesting! I've never seen a cross-validation analysis with results that look like that and I'm not quite sure what to make of them. Can you share the code you're using to run `x.validation`?
> > W/r/t which replicate you should use, my answer would be neither. Each cross-validation replicate is using only a subset of the data (the training set). So, if you want to give final results for a single model that you've selected, you should run that model using all the data (with the `conStruct` function, rather than with `x.validation`).
> 
> Hello I used an updated datasets with additional populations (300+ samples, 26 populations, 7.5K SNPs). Here is the code for the x-validation
> 
> `my.xvals <- x.validation(train.prop = 0.9, n.reps = 10, K = 1:7, freqs = pop_allele_freq_tb, data.partitions = NULL, geoDist = geodist, coords = GSC, prefix = "cross-val", n.iter = 5000, make.figs = TRUE, save.files = TRUE, parallel = TRUE, n.nodes = 30)`
> 
> `sp.results <- as.matrix( read.table("cross-val_sp_xval_results.txt", header = TRUE, stringsAsFactors = FALSE) ) nsp.results <- as.matrix( read.table("cross-val_nsp_xval_results.txt", header = TRUE, stringsAsFactors = FALSE) )` `par(mfrow=c(1,3)) plot(rowMeans(sp.results), pch=19,col="blue", ylab="predictive accuracy",xlab="values of K", ylim=range(sp.results,nsp.results), main="cross-validation results") points(rowMeans(nsp.results),col="green",pch=19)
> 
> plot(rowMeans(sp.results), pch=19,col="blue", ylab="predictive accuracy",xlab="values of K", ylim=range(sp.CIs), main="spatial cross-validation results") segments(x0 = 1:nrow(sp.results), y0 = sp.CIs[1,], x1 = 1:nrow(sp.results), y1 = sp.CIs[2,], col = "blue",lwd=2)
> 
> plot(rowMeans(nsp.results), pch=19,col="green", ylab="predictive accuracy",xlab="values of K", ylim=range(nsp.CIs), main="non-spatial cross-validation results") segments(x0 = 1:nrow(nsp.results), y0 = nsp.CIs[1,], x1 = 1:nrow(nsp.results), y1 = nsp.CIs[2,], col = "green",lwd=2)`
> 
> The result look like this
> 
> ![00000f](https://user-images.githubusercontent.com/57223771/265767869-ab6ad7bb-44e0-49f8-984a-e389be052f5d.png)
> 
> What is a good next step in selecting a best K and model for data interpretation?

the dataset has 15% variant missing which was mode imputed, and moderate LD removed.

**Comment by Dahn-YoungDong** [comment]
The updated x-validation with more repliates and MCMC iterations, look like this with reduced Confidence interval
![cross-validation-1e4-results](https://github.com/gbradburd/conStruct/assets/57223771/6832de9c-c4f1-41af-bb14-31dbfa3c9fae)

**Comment by gbradburd** [comment]
Hm well those are certainly unusual looking.  You mentioned pruning for moderate LD - it's possible that remaining LD between loci in the training and testing dataset is artificially inflating the predictive accuracy across models (see the vignette on `model-comparison` for more information).  If I were in your shoes, I would probably focus on using the layer contributions for model comparison (more than the cross-validation results).

**Comment by gbradburd** [comment]
Hi Dahn-young - just doing some New Year book-keeping. Is this issue still open for you?  If not, feel free to close it (or I can).

**Comment by Dahn-YoungDong** [comment]
Hello, I found out that my input dataset was not imputed for missingness, due to script management reason. After BEAGLE impute, it worked much better. Though the spatial predicted accuracy is only marginally better than the non-spatial, suggesting the impact of IBD may be limited in the sampling range. 

I will close this issue now. Thank you
