### ISSUE TITLE
only 250 iterations are saved on construct analysis regardless of n.iter value

### ISSUE THREAD

**Issue by monicafahey** [gbradburd/conStruct#62]
Hello!

No matter what number I specify for n.iter in the construct function, only 250 iterations are saved in the results Robj or the pdf output. I can see that all the specified iterations are being performed, but it is not being recorded. Consequently I cannot improve the ESS by increasing the chain length. I am not getting any memory errors, so not sure what is could be. 

n.chains is working as it should..

Kind regards
Monica

**Comment by gbradburd** [comment]
Hi Monica,

See my answer to this questions in Issue #16. Increasing the number of iterations for which you're running the model should improve the ESS even though the summarized output only contains 250 thinned samples from the chain (the thinned samples will just be separated by increasingly large number of intervening thinned steps).

hope that helps!
-Gideon

**Comment by monicafahey** [comment]
Thank you Gideon! Sorry I did not see that earlier post…
Cheers
Monica

**Comment by gbradburd** [comment]
No problem!  I'm going to close this issue, but feel free to reopen if it's not resolved (or to open a new one if something else comes up)!
