### ISSUE TITLE
x.validation failed : Error in { : task 1 failed - "need finite 'xlim' values"

### ISSUE THREAD

**Issue by monicafahey** [gbradburd/conStruct#64]
Hi Gideon and conStruct users

After a successful test run assuming k=3, I tried the x.validation function to compare k=1:3. When the analysis reached k=2, the run terminated with the following error message 

Error in { : task 1 failed - "need finite 'xlim' values"

As the output is not saved until the end of the analysis, I am not able to diagnose where is the stumbling block. I believe this error occurs when a data object has only NA  or non-numeric values... I can't think why this would be the case if the datablock previously worked...

Any diagnostic suggestions would be greatly appreciated!

(I have re-started the run just in case it decides to work...)

Cheers
Monica

**Comment by gbradburd** [comment]
Hi Monica,

Huh were there any errors upstream of that one?  Either way, if you set `make.figs=FALSE` in the `x.validation` arguments then it won't try to plot things, which should hopefully help you complete the run and diagnose the issue.

**Comment by gbradburd** [comment]
Hi Monica - just doing some New Year book-keeping. Is this issue still open for you?

**Comment by monicafahey** [comment]
Hi Gideon

Apologies for the delayed reply. I have not found a solution. I’ve been trialling conStruct with many datasets, and so far this is the only dataset that it failed to run.

Cheers
Monica

**Comment by gbradburd** [comment]
Have you tried running x.validation on this dataset while setting `make.figs=FALSE`?  That would help diagnose the issue, as the run could hopefully complete.

**Comment by monicafahey** [comment]
Hi Gideon, apologies for the late reply.


I re-ran with make.figs=FALSE and when I try to manually plot the admixture proportions for K>1, I get the same xlim error. Strange as there are no NAs or unusual looking numbers... I've attached the data.block and conStruct.results objects from one of the runs.


Thanks for your help,

Monica

**Comment by gbradburd** [comment]
looks like they didn't attach!  you may have to compress them first - not sure whether github allows uploading .Robjs, but it does allow .tar.gz I think.

**Comment by monicafahey** [comment]
[FicuCoro_DFi19-4841_nsp_rep1K3_conStruct.results.Robj.tar.gz](https://github.com/gbradburd/conStruct/files/14215612/FicuCoro_DFi19-4841_nsp_rep1K3_conStruct.results.Robj.tar.gz)
[FicuCoro_DFi19-4841_nsp_rep1K3_data.block.Robj.tar.gz](https://github.com/gbradburd/conStruct/files/14215615/FicuCoro_DFi19-4841_nsp_rep1K3_data.block.Robj.tar.gz)

Hopefully this works!

**Comment by gbradburd** [comment]
Hm nothing seems obviously wrong here.  Can you send the code snippet and (compressed) data you're using to run `x.validation`?

**Comment by monicafahey** [comment]
CS <- load(“path/to/ FicuCoro_DFi19-4841.rda”)

my.xvals <- x.validation(train.prop = 0.9,
                         n.reps = 5,
                         K = 1:5,
                         freqs = cs$freq,
                         data.partitions = NULL,
                         geoDist = cs$dist,
                         coords = cs$lon_lat,
                         prefix =cs$prefix,
                         n.iter = 100000,
                         make.figs = TRUE,
                         parallel = TRUE,
                         n.nodes = 50,
                         save.files = TRUE)

[FicuCoro_DFi19-4841.rda.tar.gz](https://github.com/gbradburd/conStruct/files/14273112/FicuCoro_DFi19-4841.rda.tar.gz)

**Comment by gbradburd** [comment]
Looks like you're missing lat/long information for the "Deua" sample in `cs$lon_lat` (they're listed as `NA`).  When I drop that sample from the dataset, everything runs fine.

**Comment by gbradburd** [comment]
Hey Monica! Just following up on this - did this resolve your issue?

**Comment by monicafahey** [comment]
Hello! Yes it did. My silly mistake!

Thank you,
Monica
________________________________
